language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sassy-starter' ]; then cd .. && eval "mv $currentfolder generator-sassy-starter" && cd generator-sassy-starter; fi

